services:
  hr-app:
    build:
      context: .
      network: host
    container_name: hr-ai-agent
    network_mode: host
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped

  hr-bot:
    build:
      context: .
      network: host
    container_name: hr-ai-bot
    network_mode: host
    command: ["python", "bot.py"]
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
