"""tags segments organization_tags do_not_contact

Revision ID: 21bc8c335735
Revises: ac47a81a7a38
Create Date: 2026-08-19 12:28:08.668395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21bc8c335735'
down_revision: Union[str, None] = 'ac47a81a7a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filter', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_tags',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=128), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'tag'),
    sa.UniqueConstraint('organization_id', 'tag', name='pk_org_tags')
    )
    op.add_column('candidates', sa.Column('tags', sa.ARRAY(sa.Text()), server_default='{}', nullable=False))
    op.create_index('ix_candidates_tags', 'candidates', ['tags'], unique=False, postgresql_using='gin')
    op.add_column('persons', sa.Column('tags', sa.ARRAY(sa.Text()), server_default='{}', nullable=False))
    op.create_index('ix_persons_tags', 'persons', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_segments_org_user', 'candidate_segments', ['organization_id', 'user_id'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_segments_org_user', table_name='candidate_segments')
    op.drop_index('ix_persons_tags', table_name='persons')
    op.drop_column('persons', 'tags')
    op.drop_index('ix_candidates_tags', table_name='candidates')
    op.drop_column('candidates', 'tags')
    op.drop_table('organization_tags')
    op.drop_table('candidate_segments')
